<div class="inner_right">
<h1> Corpus of Early Medieval Coin Finds</h1>
<p>The EMC database grew out of individual initiatives to record single-finds of coins from the period AD 410-1180 on the part of D. M. Metcalf, Mark Blackburn, Mike Bonser and others. Growth in the use of metal-detectors during the 1970's and 1980's led to a rapid rise in the number of such finds, and in 1987 efforts to record them were consolidated with the establishment of an annual 'Coin Register', printed in the <i> British Numismatic Journal. </i></p>
</br><p> A decade later, Mark Blackburn, Keeper of Coins at the Fitzwilliam Museum in Cambridge, began a project that would combine the strengths of the 'Coin Register' and other publications of coin-finds with the reach and flexibility of the internet. With financial support from the Leverhulme Trust, he established the Corpus of Early Medieval Coin Finds (EMC) in 1996, based in the Deparment of Coins and Medals at the Fitzwilliam Museum. The EMC website became accessible to the public in 1997, and the initial database of finds included over 6,000 records by 2001. The EMC database now contains more than 12,000 records from across England and Wales. It continues to grow at the rate of 300-400 new coin-finds per year.</p>
</br><h3> Sylloge of Coins of the British Isles </h3>
</br><p>The British Sylloge project was first proposed in the early 1950's by Christopher Blunt and other members of the Birtish and Royal Numismatic Soieties. An informal committee was formed under the chairmanship of the historian Sir Frank Stenton, who in 1956 secured its admission as a Committee of the British Academy. The first volume, on Anglo-Saxon coins in the Fitzwilliam Museum, Cambridge was published by the British Academy in 1958. Since that time it has published over 70 volumes.</p>
</br><p>The aim of the series is to publish detailed and fully illustrated catalogues of coins of the British Isles in British and other collections. The volumes range in scope from pre-Roman British coins to seventeenth-century tokens, with most detailed coverage of the Anglo-Saxon coinage. The collections recorded include those in more than two hundred national, university and provincial museums in Britain and Ireland and of museums in Scandinavia, Germany, Poland, Latvia, Estonia, Russia and the United States of America. </p>
</br><p> The digitised form of SCBI was created as a complement to the EMC database in the early 2000s, based on material in the first 50 volumes that dated to the period c. 410-1180. Coins from subsquent volumes will be added to the database in the near future.</p>
</br><h3> The importance of single finds </h3>
</br>
<p> Single-finds are coins that are thought to have been lost individually, presumably by chance, as they circulated from hand to hand. They are therefore quite different from coin hoards, which are more likely to be the result of deliberate selection and concealment. Hoards shed important light on what coins could be available at one time, and on reactions to military and other crises, but are a much less reliable gauge of the overall shape of the monetary economy.</p>
</br>
<p>Single-finds represent a window onto where and how coined money was used in the early Middle Ages. This body of material has grown out of all recognition since the first popularisation of the metal detector in the 1970s. Before that time, the appearance of a single new early medieval coin through a chance find or an archaeological excavation was an event worthy of a dedicated publication. Now, hundreds of coins of this period come to light every year. They are reported voluntarily by numerous metal-detector users across England and

Wales, who know the value of contributing their discoveries to the database, so that they can be accessed by researchers and the general public. Finders are encouraged to submit as much detail about the location and context of their discoveries as they feel comfortable with, and they should bear in mind that some information can be recorded privately without being released to the public.</p>
</br>
<p>Taken on its own, one single-find has very little to tell. But when thousands can be surveyed through the EMC database, it is possible to reach major new conclusions about the changing shape of the early medieval economy. It is thanks to the single-finds that a remarkable surge in the scale of England’s coinage can be identified in the period from about 680 to 750. Across a zone extending roughly east and south from Yorkshire to Dorset, small thick silver pennies were used and lost very extensively. On the basis of single-finds, this has emerged as the richest period of coin-use in the area between about 400 and 1200. Single-finds have also reshaped understanding of the geography of coin-use. It is now possible to track in detail the different patterns of circulation of various coin-types, or of coins from particular mint-towns in the tenth century and after.</p>
</br>
<p>Single-finds have brought a whole new category of find-context to prominence: the so-called ‘productive site’. This is a term coined by numismatists to refer to a series of locations (mostly in eastern England) that have produced large numbers of single-finds and other metallic objects in close proximity, but which are not thought to represent a dispersed hoard. Rather, they are believed to be places where coins were used especially intensively. Discoveries made by detectorists at ‘productive sites’, reported to EMC and other databases, have paved the way for further archaeological and historical investigation, often with dramatic results. At Torksey in Lincolnshire, a number of detectorists working over several decades have recovered a large quantity early medieval material, including coins of English, Frankish and Arabic origin, pieces of hack-silver and hack-gold, weights, and much more besides. The fields where these finds occurred are now believed to be the site of an encampment where the viking ‘Great Army’ spent the winter of 873/4. At Rendlesham in Suffolk, close to the famous early Anglo-Saxon cemetery of Sutton Hoo, detectorists have uncovered over many years a large assemblage of gold and silver coins from the seventh and eighth centuries, and other associated items. Thanks to subsequent surveying and excavation, these now form a major part in understanding a prominent royal site, in the Leverhulme-funded project Lordship and Landscape in East Anglia AD 400−800:<a href="http://www.ucl.ac.uk/archaeology/research/directory/lordship-landscape-east-anglia"> http://www.ucl.ac.uk/archaeology/research/directory/lordship-landscape-east-anglia</a> </p>
</br>
<p>As the body of single-find data expands, it continues to prompt fresh research. Other productive lines of approach have included examination of the potential biases in the data, at both a local and national level; comparisons between hoard data and single-finds; and the relationship between coin-finds and various aspects of the historical record, such as the distribution of wealth in Domesday Book or the occurrence of known viking raids or Old Norse place-names.</p>
</div>
